<?xml version="1.0"?>
<robot name="Mclaren_p1" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Parameters -->
 <xacro:property name="wheel_radius" value="0.15"/>       
 <xacro:property name="wheel_width"  value="0.08"/>
 <xacro:property name="wheel_mass"   value="1.5"/>
 <xacro:property name="body_length"  value="1.0"/>           
 <xacro:property name="body_width"   value="0.6"/>     
 <xacro:property name="body_height"  value="0.15"/>         
 <xacro:property name="body_mass"    value="6.0"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
      <geometry><box size="${body_length} ${body_width} ${body_height}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
      <geometry><box size="${body_length} ${body_width} ${body_height}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${body_mass}"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
  </link>
  
  
  
  <!-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ lidar mount â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ -->
<link name="lidar_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <!-- cylinder axis = +Z, full length = 0.30â€¯m -->
    <geometry><cylinder radius="0.04" length="0.1"/></geometry>
    <material name="LidarRed"><color rgba="1 0 0 1"/></material>
  </visual>

  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry><cylinder radius="0.03" length="0.1"/></geometry>
  </collision>

  <inertial>
    <mass value="0.1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.01" iyy="0.01" izz="0.01"
             ixy="0" ixz="0" iyz="0"/>
  </inertial>
</link>

<!-- Attach mast to chassis at (0.3, 0, 0.40) -->
<joint name="lidar_joint" type="fixed">
  <parent link="base_link"/>
  <child  link="lidar_link"/>
  <origin xyz="0.35 0 0.2" rpy="0 0 0"/>
</joint>

<!-- Gazebo ray sensor placed on mast top (+0.15â€¯m) -->
<gazebo reference="lidar_link">
  <sensor name="lidar_sensor" type="ray">
    <!-- Pose is relative to lidar_link -->
    <pose>0 0 0.2 0 0 0</pose>
    <visualize>true</visualize>
    <update_rate>10</update_rate>

    <ray>
      <scan>
        <horizontal>
          <samples>720</samples>
          <resolution>1</resolution>
          <min_angle>-1.5708</min_angle>   <!-- -90Â° -->
          <max_angle> 1.5708</max_angle>   <!-- +90Â° -->
        </horizontal>
      </scan>
      <range>
        <min>0.08</min>
        <max>10.0</max>
        <resolution>0.01</resolution>
      </range>
    </ray>

 <plugin name="gazebo_ros_laser_controller"
            filename="libgazebo_ros_ray_sensor.so">
      <!-- publish LaserScan on /scan -->
      <topicName>/scan</topicName>
      <frame_name>lidar_link</frame_name>
      <output_type>sensor_msgs/LaserScan</output_type>


      <ros>
        <remapping>~/out:=scan</remapping>
      </ros>
    </plugin>
  </sensor>
</gazebo>


<!-- Camera link -->
<link name="camera_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.05 0.05 0.05"/>
    </geometry>
    <material name="gray">
      <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.05 0.05 0.05"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.05"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
  </inertial>
</link>


<joint name="camera_joint" type="fixed">
  <parent link="base_link"/>
  <child link="camera_link"/>
  <origin xyz="0.35 0 0.275" rpy="0 0 0"/> <!-- Adjust position as needed -->
</joint>

<gazebo reference="camera_link">
  <sensor name="camera_sensor" type="camera">
    <pose>0 0 0 0 0 0</pose> <!-- position relative to camera_link -->
    <visualize>true</visualize>
    <update_rate>30.0</update_rate>
    <camera>
      <horizontal_fov>1.3962634</horizontal_fov> <!-- 80 degrees -->
      <image>
        <width>640</width>
        <height>480</height>
        <format>R8G8B8</format>
      </image>
      <clip>
        <near>0.1</near>
        <far>100</far>
      </clip>
    </camera>
    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
      <ros>
        <remapping>image_raw:=/camera/image_raw</remapping>
      </ros>
      <camera_name>camera</camera_name>
      <frame_name>camera_link</frame_name>
    </plugin>
  </sensor>
</gazebo>




  <!-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ wheel macro â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ -->
  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}">
      <!-- ðŸ†• rotate cylinder 90â€¯deg about X so its axis is +Y -->
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
      </surface>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${0.5*wheel_mass*wheel_radius*wheel_radius}"
          iyy="${0.5*wheel_mass*wheel_radius*wheel_radius}"
          izz="${0.5*wheel_mass*wheel_radius*wheel_radius}"
          ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${name}"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis   xyz="0 1 0"/>
    </joint>
  </xacro:macro>
  
  <xacro:wheel name="front_left_wheel"  x=" 0.35" y=" 0.35" z="0"/>
  <xacro:wheel name="front_right_wheel" x=" 0.35" y="-0.35" z="0"/>
  <xacro:wheel name="back_left_wheel"   x="-0.35" y=" 0.35" z="0"/>
  <xacro:wheel name="back_right_wheel"  x="-0.35" y="-0.35" z="0"/>



  <gazebo reference="base_link"><material>Gazebo/Green</material></gazebo>
  <gazebo reference="front_left_wheel"><material>Gazebo/Red</material></gazebo>
  <gazebo reference="front_right_wheel"><material>Gazebo/Red</material></gazebo>
  <gazebo reference="back_left_wheel"><material>Gazebo/Red</material></gazebo>
  <gazebo reference="back_right_wheel"><material>Gazebo/Red</material></gazebo>

</robot>


